### ISSUE TITLE
Log spam when using nuclear drums

### ISSUE THREAD

**Issue by SIGUSR2** [ChrisAdderley/NearFutureElectrical#111] opened 2019-07-05 00:29 UTC
Using NFE 1.0.1 and KSP 1.7.x: 

When I add a "nuclear drum" on the ship editor or switch to a ship that has a nuclear drum equiped, the KSP log starts to write the ratio of fuel in the drum at a rate of ~ 10 lines/s - e.g. if the drum is full, I get a lot of "1"s. 

If while in the editor I decrease the amount of fuel in the drum, the number changes accordingly (0.9, 0.8 etc). 

I did not notice any functionality issue.

**Comment by ChrisAdderley** [comment] 2019-07-05 18:27
Could you post a log of the event? I can't reproduce this in my install.

**Comment by SIGUSR2** [comment] 2019-07-05 18:51
https://gist.github.com/SIGUSR2/32cc3176f68cb95ba02d57317482c7a4

The output starts when I'm clicking on the part in editor, before I even add it to the ship. Relevant lines start around #26157. At #26848 I delete the part from the ship.

**Comment by ChrisAdderley** [comment] 2019-07-05 19:38
Sorry, the more comprehensive `output_log.txt` is the one I'm looking for. It's more difficult to find, check out [this post](https://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/)

**Comment by SIGUSR2** [comment] 2019-07-05 20:15
Here it is. 

https://gist.github.com/SIGUSR2/f4917ee4a5ce5712a49d64aebacbdf66

**Comment by ChrisAdderley** [comment] 2019-07-05 20:25
This is all very confusing because trawling the codebase, the only thing that should even produce log messages on a consistent basis is a fuel transfer event. I'll keep looking into it.

**Comment by ChrisAdderley** [comment] 2019-07-07 04:24
Aha, the problem has been found. An old version of the dll is currently shipped with the mod in its release versions. Installing a version from a download instead of my local copy allowed me to reproduce the issue.

The next version will include a fix. If you need it urgently just take the dll file from the `dev` branch.

**Comment by SIGUSR2** [comment] 2019-07-07 10:48
Thanks! This may be closed then - glad I could help.

**Comment by ChrisAdderley** [comment] 2019-07-08 16:36
No problem. I usually keep issues open (with the `next version` tag) until they have been release to help others who might report the same problem though, so I will leave this here until then :)

**Comment by ChrisAdderley** [comment] 2019-07-09 21:18
Released with 1.0.2.

**Closed by ChrisAdderley** 2019-07-09 21:18 UTC
Labels: bug, next version, question
